services:
  ngx1:
    image: nginx
    command: sleep infinity
    working_dir: /ngx1
    volumes:
      - .:/ngx1
    ports:
    - "777:777"
    networks:
      - net1
  
  ngx2:
    image: nginx
    command: sleep infinity
    working_dir: /ngx2
    volumes:
      - .:/ngx2
    ports:
    - "778:778"
    networks:
      - net2

  client: 
    image: alpine:latest
    command: sleep infinity
    depends_on:
      - ngx1
      - ngx2
    networks:
      - net1
      - net2


networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24 

  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24 