services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # Adiciona suporte a HTTPS
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/nginx/ssl:ro # Monta os certificados SSL
    depends_on:
      - tasks

  tasks:
    image: nginx:latest
    volumes:
      - ./app:/usr/share/nginx/html:ro
    expose:
      - "80"