services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # Adiciona suporte a HTTPS
    networks:
      - net11
      - net13
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/nginx/ssl:ro # Monta os certificados SSL
    depends_on:
      - tasks

  tasks:
    image: nginx:latest
    volumes:
      - ./app:/usr/share/nginx/html:ro
    expose:
      - "80"
    networks:
      - net12
      - net13
    deploy:
      replicas: 2


networks:
  net11:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.7.0/24  
  net12:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.8.0/24

  net13: 
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.9.0/24