services:
  container1: 
    image: busybox:latest
    command: sh -c "sleep infinity"
    networks:
      - net1


  container2:
    image: busybox:latest 
    command: sh -c "sleep infinity"
    networks:
      - net2

  container3: 
    image: busybox:latest
    command: sh -c "sleep infinity"
    networks:
      - net3

  container5: 
    image: busybox:latest
    command: sh -c "sleep infinity"
    networks:
      - net5

networks: 
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24 

  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24 

  net3:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24 

  net5:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.6.0/24 

  net4:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.4.0/24
