services:
  server:
    image: python:3.13-slim
    command: python main.py
    working_dir: /server
    volumes:
      - .:/server
    ports:
    - "666:666"


  client: 
    image: busybox:latest
    command: sleep infinity